MAIN_URL = "https://glisse-en.coeur-fde.fr"

TEAMS = [
    # --- Équipes existantes ---
    {"slug": "ma-chance-moi-aussi", "name": "Ma Chance Moi Aussi", "dept": "73", "type": "entreprise", "collecte_depart": 17300 , "prop": "MCMA"},
    {"slug": "aktid", "name": "Aktid", "dept": "73", "type": "entreprise", "collecte_depart": 9255  , "prop": "MCMA"},
    {"slug": "archimed", "name": "Archimed", "dept": "69", "type": "entreprise", "collecte_depart": 10000 , "prop": "MCMA"},
    {"slug": "ma-chance-moi-aussi-2", "name": "Ma Chance Moi Aussi 2", "dept": "73", "type": "entreprise", "collecte_depart": 7030  , "prop": "MCMA"},
    {"slug": "chance-league", "name": "Chance League", "dept": "74", "type": "tribu     ", "collecte_depart": 6770  , "prop": "MCMA"},
    {"slug": "telediag", "name": "Telediag", "dept": "69", "type": "entreprise", "collecte_depart": 6470  , "prop": "MCMA"},
    {"slug": "unis-pour-ma-chance-moi-aussi", "name": "Unis Pour Ma Chance", "dept": "73", "type": "tribu     ", "collecte_depart": 5100  , "prop": "MCMA"},
    {"slug": "o-la", "name": "O-La", "dept": "69", "type": "tribu     ", "collecte_depart": 3170  , "prop": "MCMA"},
    {"slug": "fondation-poma-6", "name": "Fondation Poma 6", "dept": "73", "type": "entreprise", "collecte_depart": 3437  , "prop": ""},
    {"slug": "fondation-poma-7", "name": "Fondation Poma 7", "dept": "73", "type": "entreprise", "collecte_depart": 780   , "prop": ""},
    {"slug": "fondation-poma-8", "name": "Fondation Poma 8", "dept": "73", "type": "entreprise", "collecte_depart": 650   , "prop": ""},
    {"slug": "team-ekosport", "name": "Team Ekosport", "dept": "73", "type": "tribu     ", "collecte_depart": 561   , "prop": "MCMA"},
    {"slug": "team-sesame", "name": "Team Sesame", "dept": "38", "type": "tribu     ", "collecte_depart": 100   , "prop": "MCMA"},
    {"slug": "e-leclerc-annecy", "name": "E.Leclerc Annecy", "dept": "74", "type": "entreprise", "collecte_depart": 0     , "prop": "MCMA"},
    {"slug": "bso", "name": "BSO", "dept": "73", "type": "entreprise", "collecte_depart": 0     , "prop": "MCMA"},
    {"slug": "polytech-annecy-chambery", "name": "Polytech Annecy-Chambery", "dept": "73", "type": "tribu     ", "collecte_depart": 31    , "prop": "MCMA"},
    {"slug": "polytech-annecy-chambery-2", "name": "Polytech Annecy-Chambery 2", "dept": "73", "type": "tribu     ", "collecte_depart": 442   , "prop": "MCMA"},
    {"slug": "maped-color-peps-2", "name": "Maped Color Peps", "dept": "73", "type": "entreprise", "collecte_depart": 1035  , "prop": ""},
    {"slug": "maped-croc-croc-2", "name": "Maped Croc Croc", "dept": "73", "type": "entreprise", "collecte_depart": 880   , "prop": ""},

    # --- Nouvelles équipes (dept et type à compléter) ---
    {"slug": "priams-2", "name": "Priams                                       ", "dept": "XX", "type": "entreprise", "collecte_depart": 17422 , "prop": ""},
    {"slug": "les-bourguignons", "name": "Les Bourguignons                             ", "dept": "XX", "type": "entreprise", "collecte_depart": 12865 , "prop": ""},
    {"slug": "les-fleches-du-coeur", "name": "Les Flèches du Cœur                          ", "dept": "XX", "type": "entreprise", "collecte_depart": 11099 , "prop": ""},
    {"slug": "williams-france-en-coeur-1", "name": "Williams France en Cœur                      ", "dept": "XX", "type": "entreprise", "collecte_depart": 7480  , "prop": "WF"},
    {"slug": "loisirs-assis-evasion", "name": "Loisirs Assis Evasion                        ", "dept": "XX", "type": "tribu     ", "collecte_depart": 6360  , "prop": "LAE"},
    {"slug": "villes-et-villages-creations-1", "name": "Villes et Villages Créations                 ", "dept": "XX", "type": "entreprise", "collecte_depart": 6165  , "prop": ""},
    {"slug": "ca-des-savoie-1", "name": "CA des Savoie 1                              ", "dept": "73", "type": "entreprise", "collecte_depart": 6165  , "prop": ""},
    {"slug": "spat-s-by-esf-2", "name": "SPAT-S by ESF 2                              ", "dept": "XX", "type": "entreprise", "collecte_depart": 5212  , "prop": ""},
    {"slug": "quiberon-infiniment-solidaire-2", "name": "Quiberon Infiniment Solidaire                ", "dept": "XX", "type": "tribu     ", "collecte_depart": 4210  , "prop": "QIS"},
    {"slug": "williams-france-en-coeur-2", "name": "Williams France en Cœur 2                    ", "dept": "XX", "type": "entreprise", "collecte_depart": 4055  , "prop": "WF"},
    {"slug": "le-petit-monde-d-ugo", "name": "Le Petit Monde d'Ugo                         ", "dept": "XX", "type": "tribu     ", "collecte_depart": 3800  , "prop": "LPU"},
    {"slug": "kyfekoi-2", "name": "Kyfekoi 2                                    ", "dept": "XX", "type": "entreprise", "collecte_depart": 3610  , "prop": ""},
    {"slug": "williams-france-en-coeur-3", "name": "Williams France en Cœur 3                    ", "dept": "XX", "type": "entreprise", "collecte_depart": 3755  , "prop": "WF"},
    {"slug": "montagnes-du-coeur", "name": "Montagnes du Cœur                            ", "dept": "XX", "type": "tribu     ", "collecte_depart": 3870  , "prop": ""},
    {"slug": "bouvet-cartier-immobilier-1", "name": "Bouvet Cartier Immobilier                    ", "dept": "XX", "type": "entreprise", "collecte_depart": 3220  , "prop": ""},
    {"slug": "jeluni", "name": "Jeluni                                       ", "dept": "XX", "type": "entreprise", "collecte_depart": 3200  , "prop": ""},
    {"slug": "leon-grosse-pays-de-savoie-dauphine-1", "name": "Léon Grosse Pays de Savoie Dauphiné          ", "dept": "XX", "type": "entreprise", "collecte_depart": 3150  , "prop": ""},
    {"slug": "skilou-6", "name": "Skilou 6                                     ", "dept": "XX", "type": "tribu     ", "collecte_depart": 2500  , "prop": ""},
    {"slug": "creations-fusalp-1", "name": "Créations Fusalp                             ", "dept": "XX", "type": "entreprise", "collecte_depart": 2566  , "prop": ""},
    {"slug": "salomon", "name": "Salomon                                      ", "dept": "XX", "type": "entreprise", "collecte_depart": 2264  , "prop": ""},
    {"slug": "takamaka", "name": "Takamaka                                     ", "dept": "XX", "type": "entreprise", "collecte_depart": 2220  , "prop": ""},
    {"slug": "cagip", "name": "CAGIP                                        ", "dept": "XX", "type": "entreprise", "collecte_depart": 1829  , "prop": ""},
    {"slug": "les-pep-it", "name": "Les PEP IT                                   ", "dept": "XX", "type": "tribu     ", "collecte_depart": 1851  , "prop": ""},
    {"slug": "fonfon-team-2", "name": "Fonfon Team                                  ", "dept": "XX", "type": "tribu     ", "collecte_depart": 2000  , "prop": ""},
    {"slug": "williams-france-en-coeur-4", "name": "Williams France en Cœur 4                    ", "dept": "XX", "type": "entreprise", "collecte_depart": 1570  , "prop": "WF"},
    {"slug": "caf-la-roche-bonnevile-1", "name": "CAF La Roche Bonnevile                       ", "dept": "XX", "type": "tribu     ", "collecte_depart": 1445  , "prop": ""},
    {"slug": "aller-plus-haut-loisirs-assis-evasion", "name": "Aller Plus Haut Loisirs Assis Evasion        ", "dept": "XX", "type": "tribu     ", "collecte_depart": 1553  , "prop": "LAE"},
    {"slug": "le-grand-bornand-tourisme", "name": "Le Grand-Bornand Tourisme                    ", "dept": "74", "type": "entreprise", "collecte_depart": 1310  , "prop": ""},
    {"slug": "williams-france-en-coeur-5", "name": "Williams France en Cœur 5                    ", "dept": "XX", "type": "entreprise", "collecte_depart": 1370  , "prop": "WF"},
    {"slug": "atelier-nordic-1", "name": "Atelier Nordic                               ", "dept": "XX", "type": "tribu     ", "collecte_depart": 1275  , "prop": ""},
    {"slug": "a-chacun-sa-glisse-1", "name": "À Chacun Sa Glisse                           ", "dept": "XX", "type": "tribu     ", "collecte_depart": 1056  , "prop": ""},
    {"slug": "les-riders-solidaires", "name": "Les Riders Solidaires                        ", "dept": "XX", "type": "tribu     ", "collecte_depart": 1010  , "prop": ""},
    {"slug": "foncia-1", "name": "Foncia                                       ", "dept": "XX", "type": "entreprise", "collecte_depart": 1060  , "prop": ""},
    {"slug": "evian-resort", "name": "Evian Resort                                 ", "dept": "74", "type": "entreprise", "collecte_depart": 955   , "prop": ""},
    {"slug": "lou-teleski-d-bornand", "name": "Lou Téléski du Bornand                       ", "dept": "74", "type": "entreprise", "collecte_depart": 860   , "prop": ""},
    {"slug": "les-remontes-pentes", "name": "Les Remontées Pentes                         ", "dept": "XX", "type": "entreprise", "collecte_depart": 820   , "prop": ""},
    {"slug": "skidata-france-sas", "name": "Skidata France SAS                           ", "dept": "XX", "type": "entreprise", "collecte_depart": 810   , "prop": ""},
    {"slug": "alpysia-1", "name": "Alpysia                                      ", "dept": "XX", "type": "entreprise", "collecte_depart": 780   , "prop": ""},
    {"slug": "les-brioches-dechaines-la-fournee-doree", "name": "Les Brioches Déchaînées - La Fournée Dorée   ", "dept": "XX", "type": "entreprise", "collecte_depart": 890   , "prop": ""},
    {"slug": "all-stars-2", "name": "All Stars                                    ", "dept": "XX", "type": "tribu     ", "collecte_depart": 690   , "prop": ""},
    {"slug": "2-a-les-fondues-de-la-glisse", "name": "2A - Les Fondues de la Glisse                ", "dept": "XX", "type": "tribu     ", "collecte_depart": 680   , "prop": ""},
    {"slug": "ttge", "name": "TTGE                                         ", "dept": "XX", "type": "entreprise", "collecte_depart": 670   , "prop": ""},
    {"slug": "football-club-de-dingy-st-clair", "name": "Football Club de Dingy-St-Clair              ", "dept": "74", "type": "tribu     ", "collecte_depart": 730   , "prop": ""},
    {"slug": "les-serials-glisseurs-la-fournee-doree", "name": "Les Sérials Glisseurs - La Fournée Dorée     ", "dept": "XX", "type": "entreprise", "collecte_depart": 750   , "prop": ""},
    {"slug": "aprcal-itou-1", "name": "APRCAL Itou                                  ", "dept": "XX", "type": "tribu     ", "collecte_depart": 675   , "prop": ""},
    {"slug": "hexact", "name": "Hexact                                       ", "dept": "XX", "type": "entreprise", "collecte_depart": 575   , "prop": ""},
    {"slug": "decathlon-loisirs-assis-evasion-2", "name": "Decathlon Loisirs Assis Evasion              ", "dept": "XX", "type": "entreprise", "collecte_depart": 570   , "prop": "LAE"},
    {"slug": "le-combat-d-elena-2", "name": "Le Combat d'Elena                            ", "dept": "XX", "type": "tribu     ", "collecte_depart": 550   , "prop": ""},
    {"slug": "les-grands-coeurs-de-spie-citynetworks", "name": "Les Grands Cœurs de Spie Citynetworks        ", "dept": "XX", "type": "entreprise", "collecte_depart": 550   , "prop": ""},
    {"slug": "mairie-du-grand-bornand-1", "name": "Mairie du Grand-Bornand                      ", "dept": "74", "type": "entreprise", "collecte_depart": 530   , "prop": ""},
    {"slug": "appel-une-main-tendue-vers-la-vie", "name": "Appel - Une Main Tendue vers la Vie          ", "dept": "XX", "type": "tribu     ", "collecte_depart": 510   , "prop": ""},
    {"slug": "le-petit-monde-d-ugo-2", "name": "Le Petit Monde d'Ugo 2                       ", "dept": "XX", "type": "tribu     ", "collecte_depart": 500   , "prop": "LPU"},
    {"slug": "cousins-yo", "name": "Cousins Yo                                   ", "dept": "XX", "type": "tribu     ", "collecte_depart": 500   , "prop": ""},
    {"slug": "williams-france-en-coeur-6", "name": "Williams France en Cœur 6                    ", "dept": "XX", "type": "entreprise", "collecte_depart": 450   , "prop": "WF"},
    {"slug": "lycee-tom-morel-et-lycee-des-glieres", "name": "Lycée Tom Morel et Lycée des Glières         ", "dept": "74", "type": "tribu     ", "collecte_depart": 406   , "prop": ""},
    {"slug": "decathlon-loisirs-assis-evasion", "name": "Decathlon Loisirs Assis Evasion              ", "dept": "XX", "type": "entreprise", "collecte_depart": 400   , "prop": "LAE"},
    {"slug": "association-reves-1", "name": "Association Rêves                            ", "dept": "XX", "type": "tribu     ", "collecte_depart": 400   , "prop": ""},
    {"slug": "laurette-fugain", "name": "Laurette Fugain                              ", "dept": "XX", "type": "tribu     ", "collecte_depart": 395   , "prop": ""},
    {"slug": "aprcal-in-1", "name": "APRCAL In                                    ", "dept": "XX", "type": "tribu     ", "collecte_depart": 440   , "prop": ""},
    {"slug": "les-vedettes", "name": "Les Vedettes                                 ", "dept": "XX", "type": "tribu     ", "collecte_depart": 385   , "prop": ""},
    {"slug": "les-pates-au-beurre", "name": "Les Pâtes au Beurre                          ", "dept": "XX", "type": "tribu     ", "collecte_depart": 370   , "prop": "LPB"},
    {"slug": "prevost-2", "name": "Prevost                                      ", "dept": "XX", "type": "entreprise", "collecte_depart": 455   , "prop": ""},
    {"slug": "ainr-oxyski", "name": "AINR Oxyski                                  ", "dept": "XX", "type": "tribu     ", "collecte_depart": 425   , "prop": ""},
    {"slug": "danse-en-coeur-6", "name": "Danse en Cœur                                ", "dept": "XX", "type": "tribu     ", "collecte_depart": 310   , "prop": ""},
    {"slug": "women-safe-haute-savoie", "name": "Women Safe Haute-Savoie                      ", "dept": "74", "type": "tribu     ", "collecte_depart": 330   , "prop": ""},
    {"slug": "daa-aravis", "name": "DAA Aravis                                   ", "dept": "74", "type": "tribu     ", "collecte_depart": 300   , "prop": ""},
    {"slug": "les-ischios-du-coeur", "name": "Les Ischios du Cœur                          ", "dept": "XX", "type": "tribu     ", "collecte_depart": 530   , "prop": ""},
    {"slug": "li2c", "name": "Li2C                                         ", "dept": "XX", "type": "entreprise", "collecte_depart": 270   , "prop": ""},
    {"slug": "apdc-les-commercants-du-chinaillon", "name": "APDC - Les Commerçants du Chinaillon         ", "dept": "74", "type": "entreprise", "collecte_depart": 260   , "prop": ""},
    {"slug": "apres-la-pluie-1", "name": "Après la Pluie                               ", "dept": "XX", "type": "tribu     ", "collecte_depart": 250   , "prop": ""},
    {"slug": "dravengers-1", "name": "Dravengers                                   ", "dept": "XX", "type": "tribu     ", "collecte_depart": 230   , "prop": ""},
    {"slug": "les-gazelles-les-puits-du-desert-1", "name": "Les Gazelles - Les Puits du Désert           ", "dept": "XX", "type": "tribu     ", "collecte_depart": 240   , "prop": ""},
    {"slug": "dravengers-by-altius-1", "name": "Dravengers by Altius                         ", "dept": "XX", "type": "entreprise", "collecte_depart": 275   , "prop": ""},
    {"slug": "les-fondus-du-coeur", "name": "Les Fondus du Cœur                           ", "dept": "XX", "type": "tribu     ", "collecte_depart": 220   , "prop": ""},
    {"slug": "halpades-en-choeur", "name": "Halpades en Chœur                            ", "dept": "XX", "type": "tribu     ", "collecte_depart": 210   , "prop": ""},
    {"slug": "vendee-coeur-1", "name": "Vendée Cœur                                  ", "dept": "XX", "type": "tribu     ", "collecte_depart": 250   , "prop": ""},
    {"slug": "hagopig-2", "name": "Hagopig 2                                    ", "dept": "XX", "type": "tribu     ", "collecte_depart": 90    , "prop": ""},
    {"slug": "les-benevoles-en-coeur-1", "name": "Les Bénévoles en Cœur                        ", "dept": "XX", "type": "tribu     ", "collecte_depart": 160   , "prop": ""},
    {"slug": "les-pompiers-du-grand-bo-3", "name": "Les Pompiers du Grand-Bo 3                   ", "dept": "74", "type": "tribu     ", "collecte_depart": 150   , "prop": ""},
    {"slug": "chateau-de-lagarde-team-arnaud-boissieres", "name": "Château de Lagarde - Team Arnaud Boissières  ", "dept": "XX", "type": "tribu     ", "collecte_depart": 150   , "prop": ""},
    {"slug": "deyrier-village-1", "name": "Deyrier Village 1                            ", "dept": "74", "type": "tribu     ", "collecte_depart": 200   , "prop": ""},
    {"slug": "snow", "name": "Snow                                         ", "dept": "XX", "type": "entreprise", "collecte_depart": 219   , "prop": ""},
    {"slug": "raffin-et-associes", "name": "Raffin et Associés                           ", "dept": "XX", "type": "entreprise", "collecte_depart": 120   , "prop": ""},
    {"slug": "la-team-bontaz", "name": "La Team Bontaz                               ", "dept": "XX", "type": "entreprise", "collecte_depart": 115   , "prop": ""},
    {"slug": "ifsi-ambilly-2", "name": "IFSI Ambilly 2                               ", "dept": "74", "type": "tribu     ", "collecte_depart": 160   , "prop": ""},
    {"slug": "reves", "name": "Rêves                                        ", "dept": "XX", "type": "tribu     ", "collecte_depart": 110   , "prop": ""},
    {"slug": "groupe-plenetude-6", "name": "Groupe Plénétude 6                           ", "dept": "XX", "type": "entreprise", "collecte_depart": 120   , "prop": ""},
    {"slug": "kiwanis-annemasse-annecy", "name": "Kiwanis Annemasse-Annecy                     ", "dept": "74", "type": "tribu     ", "collecte_depart": 100   , "prop": ""},
    {"slug": "colas-2", "name": "Colas 2                                      ", "dept": "XX", "type": "entreprise", "collecte_depart": 100   , "prop": ""},
    {"slug": "mission-glisse", "name": "Mission Glisse                               ", "dept": "XX", "type": "tribu     ", "collecte_depart": 1350  , "prop": ""},
    {"slug": "les-fous-du-tire-fesse", "name": "Les Fous du Tire-Fesse                       ", "dept": "XX", "type": "tribu     ", "collecte_depart": 100   , "prop": ""},
    {"slug": "mission-coeur", "name": "Mission Cœur                                 ", "dept": "XX", "type": "tribu     ", "collecte_depart": 1200  , "prop": ""},
    {"slug": "in-extenso-1", "name": "In Extenso 1                                 ", "dept": "XX", "type": "entreprise", "collecte_depart": 80    , "prop": ""},
    {"slug": "peakimmo-primalp", "name": "Peakimmo Primalp                             ", "dept": "XX", "type": "entreprise", "collecte_depart": 60    , "prop": ""},
    {"slug": "mmv-demathieu", "name": "MMV Demathieu                                ", "dept": "XX", "type": "entreprise", "collecte_depart": 60    , "prop": ""},
    {"slug": "la-reserve", "name": "La Réserve                                   ", "dept": "XX", "type": "entreprise", "collecte_depart": 50    , "prop": ""},
    {"slug": "synergihp", "name": "Synergihp                                    ", "dept": "XX", "type": "tribu     ", "collecte_depart": 50    , "prop": ""},
    {"slug": "les-pompiers-d-epagny-2", "name": "Les Pompiers d'Epagny 2                      ", "dept": "74", "type": "tribu     ", "collecte_depart": 50    , "prop": ""},
    {"slug": "iriig-2", "name": "IRIIG 2                                      ", "dept": "XX", "type": "entreprise", "collecte_depart": 100   , "prop": ""},
    {"slug": "glisseforgood", "name": "GlisseForGood                                ", "dept": "XX", "type": "tribu     ", "collecte_depart": 40    , "prop": "MCMA"},
    {"slug": "les-pompiers-du-grand-bo-1", "name": "Les Pompiers du Grand-Bo 1                   ", "dept": "74", "type": "tribu     ", "collecte_depart": 30    , "prop": ""},
    {"slug": "les-chameaux-les-puits-du-desert", "name": "Les Chameaux - Les Puits du Désert           ", "dept": "XX", "type": "tribu     ", "collecte_depart": 165   , "prop": ""},
    {"slug": "groupe-plenetude-7", "name": "Groupe Plénétude 7                           ", "dept": "XX", "type": "entreprise", "collecte_depart": 20    , "prop": ""},
    {"slug": "roule-en-coeur", "name": "Roule en Cœur                                ", "dept": "XX", "type": "tribu     ", "collecte_depart": 0     , "prop": "QIS"},
    {"slug": "allianz-bresson-guette-sauve-1", "name": "Allianz Bresson Guette Sauvé 1               ", "dept": "XX", "type": "entreprise", "collecte_depart": 0     , "prop": ""},
    {"slug": "dassault-aviation-business-services", "name": "Dassault Aviation Business Services          ", "dept": "XX", "type": "entreprise", "collecte_depart": 0     , "prop": ""},
    {"slug": "la-croix-saint-maurice-1", "name": "La Croix Saint-Maurice 1                     ", "dept": "XX", "type": "tribu     ", "collecte_depart": 0     , "prop": ""},
    {"slug": "rotaract-1781", "name": "Rotaract 1781                                ", "dept": "XX", "type": "tribu     ", "collecte_depart": 0     , "prop": ""},
    {"slug": "publi-decoup-by-id-1", "name": "Publi-Découp by ID 1                         ", "dept": "XX", "type": "entreprise", "collecte_depart": 100   , "prop": ""},
    {"slug": "baouw", "name": "Baouw                                        ", "dept": "XX", "type": "entreprise", "collecte_depart": 0     , "prop": ""},
    {"slug": "rotaract-district-1710", "name": "Rotaract District 1710                       ", "dept": "XX", "type": "tribu     ", "collecte_depart": 0     , "prop": ""},
    {"slug": "alvean-2", "name": "Alvean 2                                     ", "dept": "XX", "type": "entreprise", "collecte_depart": 0     , "prop": ""},
    {"slug": "team-mg", "name": "Team MG                                      ", "dept": "XX", "type": "tribu     ", "collecte_depart": 50    , "prop": "MCMA"},
    {"slug": "hagopig-5", "name": "Hagopig 5                                    ", "dept": "XX", "type": "tribu     ", "collecte_depart": 180   , "prop": ""},
    {"slug": "skilou-7", "name": "Skilou 7                                     ", "dept": "XX", "type": "tribu     ", "collecte_depart": 0     , "prop": ""},
    {"slug": "cgh-complice-de-la-glisse", "name": "CGH Complice de la Glisse                    ", "dept": "XX", "type": "entreprise", "collecte_depart": 4     , "prop": ""},
    {"slug": "creations-fusalp-3", "name": "Créations Fusalp 3                           ", "dept": "XX", "type": "entreprise", "collecte_depart": 0     , "prop": ""},
]

DUEL_TEAM_1 = "aktid"
DUEL_TEAM_2 = "archimed"

DUEL_DEPT_1 = "73"
DUEL_DEPT_2 = "74"
DUEL_DEPT_1_NAME = "Savoie"
DUEL_DEPT_2_NAME = "Haute-Savoie"

REPORT_HOUR = 9
SCRAPE_INTERVAL_MINUTES = 60